# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-31 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='CreateDate'),
        ),
    ]
